# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

points_cpp <- function(pts, gdim = "XY") {
    .Call(`_sfcc_points_cpp`, pts, gdim)
}

multipoints_cpp <- function(pts, scanindex = -1L, gdim = "XY") {
    .Call(`_sfcc_multipoints_cpp`, pts, scanindex, gdim)
}

